/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_Chat_Menja;

import io.skaarup.Client;
import io.skaarup.Message;
import io.skaarup.Notification;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Menja
 */
public class GUI_Chat_Menja extends javax.swing.JFrame implements Observer {

    Client c = null;

    /**
     * Creates new form GUI_Chat
     */
    public GUI_Chat_Menja() {
        initComponents();
        c = new Client("localhost", 8081, "Menja");
        c.addObserver(this);
        c.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IpAddress = new javax.swing.JTextField();
        TargetPort = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageArea = new javax.swing.JTextArea();
        SendMessageField = new javax.swing.JTextField();
        SendMessageButton = new javax.swing.JButton();
        ReceivingPort = new javax.swing.JTextField();
        ListenButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IpAddress.setName("IpAddress"); // NOI18N
        IpAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IpAddressActionPerformed(evt);
            }
        });

        TargetPort.setName("TargetPort"); // NOI18N
        TargetPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TargetPortActionPerformed(evt);
            }
        });

        MessageArea.setColumns(20);
        MessageArea.setRows(5);
        MessageArea.setName("MessageArea"); // NOI18N
        jScrollPane1.setViewportView(MessageArea);

        SendMessageField.setName("SendMessageField"); // NOI18N

        SendMessageButton.setText("Send");
        SendMessageButton.setName("SendButton"); // NOI18N
        SendMessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendMessageButtonActionPerformed(evt);
            }
        });

        ReceivingPort.setName("ReceivingPort"); // NOI18N

        ListenButton.setLabel("Listen");
        ListenButton.setName("ListenButton"); // NOI18N
        ListenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListenButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ListenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ReceivingPort, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TargetPort, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SendMessageField)
                        .addGap(18, 18, 18)
                        .addComponent(SendMessageButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TargetPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReceivingPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListenButton)
                    .addComponent(IpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SendMessageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SendMessageButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TargetPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TargetPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TargetPortActionPerformed

    private void IpAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IpAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IpAddressActionPerformed
//    MessageListener_Menja messageListener;
    private void ListenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListenButtonActionPerformed
        // TODO add your handling code here:
//        DONT NEED THIS
//        messageListener = new MessageListener_Menja(this, Integer.parseInt(ReceivingPort.getText()));
//        
//        messageListener.start();
    }//GEN-LAST:event_ListenButtonActionPerformed

//    MessageTransmitter_Menja mt = null;
    private void SendMessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendMessageButtonActionPerformed
        // TODO add your handling code here:
//        if(mt == null) {
//            mt = new MessageTransmitter_Menja(IpAddress.getText(), Integer.parseInt(TargetPort.getText()));
//        } 
//        mt.setMessage(MessageArea.getText());
//        mt.start();
        if (SendMessageField.getText().trim().length() != 0) {
            c.sendMessage(new Message(SendMessageField.getText()));
            SendMessageField.setText("");
        }
    }//GEN-LAST:event_SendMessageButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Chat_Menja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Chat_Menja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Chat_Menja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Chat_Menja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUI_Chat_Menja().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IpAddress;
    private javax.swing.JButton ListenButton;
    private javax.swing.JTextArea MessageArea;
    private javax.swing.JTextField ReceivingPort;
    private javax.swing.JButton SendMessageButton;
    private javax.swing.JTextField SendMessageField;
    private javax.swing.JTextField TargetPort;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (!(arg instanceof Notification)) {
            return;
        }

        Notification n = (Notification) arg;
        switch (n.getType()) {
            case MESSAGE:
                Message m = n.getMessage();
                MessageArea.setText(MessageArea.getText() + "\n" + m.username + ": " + m.text);
                break;
            case UPDATE:
                // do something maybe
                break;
            case DELETE:
                // do something maybe
                break;
        }
    }

//    @Override
//    public void write(String s) {
//        MessageArea.append(s + System.lineSeparator());
//    }
}
